set(_CATKIN_CURRENT_PACKAGE "store_images")
set(store_images_VERSION "0.0.0")
set(store_images_MAINTAINER "tommy <tommy@todo.todo>")
set(store_images_PACKAGE_FORMAT "1")
set(store_images_BUILD_DEPENDS "rospy" "std_msgs")
set(store_images_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(store_images_BUILDTOOL_DEPENDS "catkin")
set(store_images_BUILDTOOL_EXPORT_DEPENDS )
set(store_images_EXEC_DEPENDS "rospy" "std_msgs")
set(store_images_RUN_DEPENDS "rospy" "std_msgs")
set(store_images_TEST_DEPENDS )
set(store_images_DOC_DEPENDS )
set(store_images_DEPRECATED "")